version: "2"
services:
  nvim:
    container_name: grpc-nvim
    image: iimuz/neovim:v0.3.0-slim7
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    volumes:
      - src:/src/github.com/iimuz/grpc-samples
    working_dir: /src/github.com/iimuz/grpc-samples/cpp-build

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../
      o: bind
