version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        USERNAME: $USER
        USER_UID: $USER_UID
        USER_GID: $USER_GID
    init: true
    working_dir: $PWD
    volumes:
      - type: bind
        source: .
        target: $PWD
    env_file: .env
    command: python src/convert-to-db.py -v
    user: $USER
