version: "3.4"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      target: withUser
      args:
        - USER_NAME=dev
        - USER_ID=1000
        - GROUP_ID=1000
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: dev
    volumes:
      - ..:/workspace
