version: "3.3"
services:
  dev:
    container_name: atcoder_dev
    network_mode: none
    image: iimuz/cpp-dev:v3.8.0-atcoder1
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    volumes:
      - src:/src:rw
    working_dir: /src/tenka1Beginer_2018/
    command: ash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../
      o: bind
