version: "3.3"
services:
  dev:
    container_name: at-tenka1-c-dev
    network_mode: none
    image: iimuz/cpp-dev:v3.8.0-atcoder1
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    volumes:
      - src:/src/github.com/iimuz/atcoder
    working_dir: /src/github.com/iimuz/atcoder/tenka1Beginer_2018/C
    command: ash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../../
      o: bind
